OCEAN_MARKET_CONTRACT = 'OceanMarket.kovan.json/OceanMarket.kovan'
OCEAN_TOKEN_CONTRACT = 'OceanToken.kovan.json/OceanToken.kovan'
OCEAN_ACL_CONTRACT = 'OceanAuth.kovan.json/OceanAuth.kovan'
KEEPER_CONTRACTS = 'keeper-contracts'
OCEAN_DID_REGISTRY_CONTRACT = 'OceanRegistry.kovan.json/OceanRegistry.kovan'
